import { Order, OrderStatus } from '@/types/order';
import { createAdminClient, isSupabaseConnected } from '@/lib/supabase-admin';

// In-memory store for mock mode (mutable array — reassigned on reset)
// eslint-disable-next-line prefer-const
let mockOrders: Order[] = [];

// Valid state transitions
const validTransitions: Record<OrderStatus, OrderStatus[]> = {
  pending: ['confirmed', 'cancelled'],
  confirmed: ['delivering', 'cancelled'],
  delivering: ['completed', 'cancelled'],
  completed: [],
  cancelled: [],
};

// Supabase select query that joins order_items with menu_items for names
const ORDER_SELECT = '*, order_items(*, menu_item:menu_items!order_items_menu_item_id_fkey(name_en, name_zh, name_ja, category))';

export async function getOrders(filter?: string): Promise<Order[]> {
  if (isSupabaseConnected()) {
    const supabase = createAdminClient()!;
    let query = supabase
      .from('orders')
      .select(ORDER_SELECT)
      .order('created_at', { ascending: false });

    if (filter === 'active') {
      query = query.in('status', ['pending', 'confirmed', 'delivering']);
    } else if (filter === 'completed') {
      query = query.eq('status', 'completed');
    } else if (filter === 'cancelled') {
      query = query.eq('status', 'cancelled');
    }

    const { data, error } = await query;
    if (error) throw error;

    return (data || []).map(transformDbOrder);
  }

  // Mock fallback
  let orders = [...mockOrders].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );

  if (filter === 'active') {
    orders = orders.filter(o => ['pending', 'confirmed', 'delivering'].includes(o.status));
  } else if (filter === 'completed') {
    orders = orders.filter(o => o.status === 'completed');
  } else if (filter === 'cancelled') {
    orders = orders.filter(o => o.status === 'cancelled');
  }

  return orders;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function createOrder(orderData: {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  items: any[];
  hotel_id?: string;
  room_number?: string;
  messenger_id?: string;
  messenger_platform?: string;
  special_request?: string;
  total_amount: number;
  delivery_fee?: number;
  order_type?: string;
  language?: string;
}): Promise<Order> {
  if (isSupabaseConnected()) {
    const supabase = createAdminClient()!;

    // Insert order — order_number is auto-generated by DB trigger
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        hotel_id: orderData.hotel_id || null,
        room_number: orderData.room_number || null,
        messenger_id: orderData.messenger_id || null,
        messenger_platform: orderData.messenger_platform || null,
        special_request: orderData.special_request || null,
        total_amount: orderData.total_amount,
        delivery_fee: orderData.delivery_fee || 0,
        order_type: orderData.order_type || 'delivery',
        status: 'pending',
        language: orderData.language || 'en',
      })
      .select()
      .single();

    if (orderError) throw orderError;

    // Insert order items
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const orderItems = orderData.items.map((item: any) => ({
      order_id: order.id,
      menu_item_id: item.menu_item_id || item.menuItemId || null,
      size: item.size || null,
      quantity: item.quantity,
      unit_price: item.unitPrice || item.unit_price,
      subtotal: (item.unitPrice || item.unit_price) * item.quantity,
      half1_item_id: item.half1_item_id || item.leftPizza?.menu_item_id || null,
      half2_item_id: item.half2_item_id || item.rightPizza?.menu_item_id || null,
      set_selections: item.set_selections || item.selectedComponents
        ? JSON.stringify(item.set_selections || item.selectedComponents)
        : null,
    }));

    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(orderItems);

    if (itemsError) throw itemsError;

    // Re-fetch the complete order with joins so transformDbOrder works correctly
    const { data: fullOrder, error: fetchError } = await supabase
      .from('orders')
      .select(ORDER_SELECT)
      .eq('id', order.id)
      .single();

    if (fetchError) throw fetchError;

    return transformDbOrder(fullOrder);
  }

  // Mock fallback
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
  const todayOrders = mockOrders.filter(o => o.order_number.includes(dateStr));
  const seq = String(todayOrders.length + 1).padStart(3, '0');

  const order: Order = {
    id: `order-${Date.now()}`,
    order_number: `POL-${dateStr}-${seq}`,
    items: orderData.items,
    hotel_id: orderData.hotel_id || '',
    room_number: orderData.room_number || '',
    messenger_id: orderData.messenger_id,
    messenger_platform: orderData.messenger_platform as Order['messenger_platform'],
    special_request: orderData.special_request,
    special_requests: orderData.special_request, // backward compat
    total_amount: orderData.total_amount,
    delivery_fee: orderData.delivery_fee || 0,
    order_type: (orderData.order_type as Order['order_type']) || 'delivery',
    language: orderData.language || 'en',
    status: 'pending',
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  };

  mockOrders.push(order);
  return order;
}

export async function updateOrderStatus(
  orderId: string,
  newStatus: OrderStatus,
  paymentMethod?: 'cash' | 'card'
): Promise<Order | null> {
  if (isSupabaseConnected()) {
    const supabase = createAdminClient()!;

    // Get current order to validate transition
    const { data: current } = await supabase
      .from('orders')
      .select('status')
      .eq('id', orderId)
      .single();

    if (!current) return null;

    const allowed = validTransitions[current.status as OrderStatus];
    if (!allowed || !allowed.includes(newStatus)) return null;

    const updateData: Record<string, unknown> = { status: newStatus };
    if (paymentMethod) updateData.payment_method = paymentMethod;

    // Set the appropriate timestamp for the new status
    const now = new Date().toISOString();
    switch (newStatus) {
      case 'confirmed':
        updateData.confirmed_at = now;
        break;
      case 'delivering':
        updateData.delivering_at = now;
        break;
      case 'completed':
        updateData.completed_at = now;
        break;
      case 'cancelled':
        updateData.cancelled_at = now;
        break;
    }

    const { data: updated, error } = await supabase
      .from('orders')
      .update(updateData)
      .eq('id', orderId)
      .select(ORDER_SELECT)
      .single();

    if (error) return null;
    return transformDbOrder(updated);
  }

  // Mock fallback
  const orderIndex = mockOrders.findIndex(o => o.id === orderId);
  if (orderIndex === -1) return null;

  const order = mockOrders[orderIndex];
  const allowed = validTransitions[order.status];
  if (!allowed.includes(newStatus)) return null;

  const updated: Order = {
    ...order,
    status: newStatus,
    payment_method: paymentMethod || order.payment_method,
    updated_at: new Date().toISOString(),
  };

  mockOrders[orderIndex] = updated;
  return updated;
}

export async function getOrderById(orderId: string): Promise<Order | null> {
  if (isSupabaseConnected()) {
    const supabase = createAdminClient()!;
    const { data } = await supabase
      .from('orders')
      .select(ORDER_SELECT)
      .eq('id', orderId)
      .single();
    if (!data) return null;
    return transformDbOrder(data);
  }

  return mockOrders.find(o => o.id === orderId) || null;
}

export async function getOrderByNumber(orderNumber: string): Promise<Order | null> {
  if (isSupabaseConnected()) {
    const supabase = createAdminClient()!;
    const { data } = await supabase
      .from('orders')
      .select(ORDER_SELECT)
      .eq('order_number', orderNumber)
      .single();
    if (!data) return null;
    return transformDbOrder(data);
  }

  return mockOrders.find(o => o.order_number === orderNumber) || null;
}

// Transform Supabase row to Order type
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function transformDbOrder(row: Record<string, any>): Order {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const items = (row.order_items || []).map((item: Record<string, any>) => ({
    id: item.id,
    type: item.menu_item?.category || 'pizza',
    name: {
      en: item.menu_item?.name_en || '',
      zh: item.menu_item?.name_zh || '',
      ja: item.menu_item?.name_ja || '',
    },
    size: item.size,
    quantity: item.quantity,
    unitPrice: item.unit_price,
  }));

  // Compute updated_at from status timestamps (DB has no updated_at column)
  const updated_at = row.cancelled_at
    || row.completed_at
    || row.delivering_at
    || row.confirmed_at
    || row.created_at;

  return {
    id: row.id,
    order_number: row.order_number,
    items,
    total_amount: row.total_amount,
    hotel_id: row.hotel_id,
    room_number: row.room_number,
    messenger_id: row.messenger_id || undefined,
    messenger_platform: row.messenger_platform || undefined,
    order_type: row.order_type || 'delivery',
    delivery_fee: row.delivery_fee || 0,
    special_request: row.special_request || undefined,
    status: row.status,
    payment_method: row.payment_method || undefined,
    language: row.language || 'en',
    created_at: row.created_at,
    updated_at,
    confirmed_at: row.confirmed_at || undefined,
    delivering_at: row.delivering_at || undefined,
    completed_at: row.completed_at || undefined,
    cancelled_at: row.cancelled_at || undefined,
  };
}

export function getTodaySettlement(orders: Order[]) {
  const completed = orders.filter(o => o.status === 'completed');
  const cash = completed.filter(o => o.payment_method === 'cash');
  const card = completed.filter(o => o.payment_method === 'card');
  const delivery = completed.filter(o => o.order_type === 'delivery');
  const pickup = completed.filter(o => o.order_type === 'pickup');

  return {
    totalRevenue: completed.reduce((s, o) => s + o.total_amount, 0),
    totalCount: completed.length,
    cashRevenue: cash.reduce((s, o) => s + o.total_amount, 0),
    cashCount: cash.length,
    cardRevenue: card.reduce((s, o) => s + o.total_amount, 0),
    cardCount: card.length,
    deliveryFeeTotal: completed.reduce((s, o) => s + (o.delivery_fee || 0), 0),
    deliveryCount: delivery.length,
    pickupCount: pickup.length,
  };
}

// For testing: get the mock store reference
export function _getMockOrders(): Order[] {
  return mockOrders;
}
